name: Build Ubuntu Touch Image

on:
  push:
    branches:
      - main
      - ubports-garnet
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Print current directory workspace
        run: |
          echo "Working directory is: $GITHUB_WORKSPACE"
          pwd
          ls -la

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            git \
            make \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            xz-utils \
            curl \
            wget \
            ca-certificates \
            kmod \
            cpio \
            python3 \
            android-sdk-libsparse-utils \
            lz4 \
            sudo \
            && sudo rm -rf /var/lib/apt/lists/*

      - name: Run build scripts
        run: |
          # Grant executable permissions to all script files in the repository
          find . -type f -name "*.sh" -exec chmod +x {} +

          # Run build process
          ./build.sh
          ./build/prepare-fake-ota.sh out/device_garnet_usrmerge.tar.xz ota
          sudo ./build/system-image-from-ota.sh ota/ubuntu_command images
          ./make-installer-images.sh
